#!/bin/sh

#########################################
# Connectivity


#########################################
# Commands to run apps


#########################################
# Commands to change dirs
alias to.dotfiles='cd ~/.dotfiles'
alias to.dropbox='cd ~/Dropbox'
alias to.desktop='cd ~/Desktop'
alias to.docs='cd ~/Documents'
alias to.git='cd ~/git'


#################################
# Simple Program Name Shortening
alias g=git


#############################
# Utilities
alias zipall='for D in *; do zip -r "$D" "$D"; done'

alias hexdumpfile='od -h'

# Git Scribe Commands
alias gitscribe.gp='git scribe gen pdf && open output/book.pdf'
alias gitscribe.gh='git scribe gen html && open output/book.html'

# Show network connections
# Often useful to prefix with SUDO to see more system level network usage
alias network.connections='lsof -l -i +L -R -V'
alias network.established='lsof -l -i +L -R -V | grep ESTABLISHED'
alias network.internalip="ifconfig en0 | egrep -o '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)'"
alias network.externalip='curl -s http://checkip.dyndns.org/ | sed "s/[a-zA-Z<>/ :]//g"'

# Files used, anywhere on the filesystem
alias files.usage='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep'
# Files being opened
alias files.open='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep open'
# Files in use in the Users directory
alias files.usage.user='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep Users'

# Directory listings
# LS_COLORS='no=01;37:fi=01;37:di=07;96:ln=01;36:pi=01;32:so=01;35:do=01;35:bd=01;33:cd=01;33:ex=01;31:mi=00;05;37:or=00;05;37:'
# -G Add colors to ls
# -l Long format
# -h Short size suffixes (B, K, M, G, P)
# -p Postpend slash to folders
alias ls='ls -G -h -p '
alias ll='ls -l -G -h -p '


#########################################
# Utility Functions

# Create a new git repo with one README commit and CD into it
function git.nr() { mkdir $1; cd $1; git init; touch README; git add README; git commit -m "First commit.";}

function find.name() {
  wild=\'\*$1\*\'
  sh -c "find . -iname $wild"
}

alias lessc='less -R' # Lets color escape sequences carry through to less
alias morec='more -R'
alias lesscolor='less -R'
alias morecolor='more -R'

